server:
  port: 8781
#指定服务中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务的名称
spring:
  application:
    name: order-service
  #redis的配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  #zipkin的配置
  zipkin:
    base-url: http://localhost:8080/
  sleuth:
    sampler:
      probability: 1
#更改负载均衡器策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#修改调用超时设置
feign:
  #开启feign支持hystrix
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000
#设置超时有效，超时时间4秒
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"